//Hotel
export const SELECT_HOTEL = 'SELECT_HOTEL';
export const SELECT_START_DATE = 'SELECT_START_DATE';
export const SELECT_END_DATE = 'SELECT_END_DATE';
export const SELECT_ADULT_SIZE = 'SELECT_ADULT_SIZE';
export const SELECT_CHILD_SIZE = 'SELECT_CHILD_SIZE';
export const RESET_HOTEL = 'RESET_HOTEL';

//Room
export const SELECT_ROOM_TYPE = 'SELECT_ROOM_TYPE';
export const SELECT_LANDSCAPE = 'SELECT_LANDSCAPE';
export const RESET_ROOM = 'RESET_ROOM';

//Payment
export const SELECT_NAME = 'SELECT_NAME';
export const SELECT_NUMBER = 'SELECT_NUMBER';
export const SELECT_MONTH = 'SELECT_MONTH';
export const SELECT_YEAR = 'SELECT_YEAR';
export const SELECT_CVV = 'SELECT_CVV'; 
export const RESET_PAYMENT = 'RESET_PAYMENT';